=== mrusoff/sd-dsl/trunk/fr.chaunier.proto.sample/src-gen/xsds/invoice_xsd.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xsd:schema xmlns:invxsd="http://www.chaunier.fr/invoice_xsd" 
attributeFormDefault="unqualified" 
elementFormDefault="unqualified" 
targetNamespace="http://www.chaunier.fr/invoice_xsd"
xmlns:xsd="http://www.w3.org/2001/XMLSchema"
xmlns:cat="http://www.p.chaunier.fr/catalogue"
xmlns:add="http://www.p.chaunier.fr/add"
>
<xsd:import schemaLocation="catalogue.xsd" namespace="http://www.p.chaunier.fr/catalogue"></xsd:import>
<xsd:import schemaLocation="address.xsd" namespace="http://www.p.chaunier.fr/add"></xsd:import>
      	<xsd:annotation>
      <xsd:documentation>InvoiceNumber</xsd:documentation>
      </xsd:annotation>
      	<xsd:annotation>
      <xsd:documentation>CustNumber</xsd:documentation>
      </xsd:annotation>
      	<xsd:annotation>
      <xsd:documentation>Description</xsd:documentation>
      </xsd:annotation>
      	<xsd:annotation>
      <xsd:documentation>Price</xsd:documentation>
      </xsd:annotation>
      	<xsd:annotation>
      <xsd:documentation>Discount</xsd:documentation>
      </xsd:annotation>
      	<xsd:annotation>
      <xsd:documentation>Date</xsd:documentation>
      </xsd:annotation>
      <xsd:complexType name="InvoiceType" >
      <xsd:sequence>
          <xsd:element name="header"  type="invxsd:HeaderType"	
          >
           </xsd:element>
          <xsd:element name="items" maxOccurs="unbounded"
           type="invxsd:ItemType"	
          >
           </xsd:element>
      </xsd:sequence>
      	</xsd:complexType>  
      <xsd:complexType name="HeaderType" >
      <xsd:sequence>
          <xsd:element name="ddate"  type="xsd:string" 
          >
           </xsd:element>
          <xsd:element name="billTo"  type="invxsd:BillToType"	
          >
           </xsd:element>
      </xsd:sequence>
      	</xsd:complexType>  
      <xsd:complexType name="BillToType" >
      <xsd:sequence>
          <xsd:element name="customerNumber"  type="xsd:string" 
          >
           </xsd:element>
          <xsd:element name="postalAddress"  type="add:PostalAddressType"	
          >
           </xsd:element>
      </xsd:sequence>
      	</xsd:complexType>  
      <xsd:complexType name="ItemType" >
      <xsd:sequence>
          <xsd:element name="publication"  type="cat:PublicationType"	
          >
           </xsd:element>
          <xsd:element name="description" maxOccurs="unbounded"
           type="xsd:string" 
          >
           </xsd:element>
          <xsd:element name="price"  type="xsd:string" 
          >
           </xsd:element>
          <xsd:element name="discount"  type="xsd:string" 
          >
           </xsd:element>
      </xsd:sequence>
      	</xsd:complexType>  
      <xsd:element name="Invoice" type="invxsd:InvoiceType"></xsd:element>
    </xsd:schema>

=== mrusoff/sd-dsl/fr.chaunier.proto.sample/src-gen/xsds/invoice_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<invxsd:Invoice xmlns:cat="http://www.p.chaunier.fr/catalogue" xmlns:invxsd="http://www.chaunier.fr/invoice_xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.chaunier.fr/invoice_xsd invoice_xsd.xsd ">
  <header>
    <ddate>ddate</ddate>
    <billTo>
      <customerNumber>customerNumber</customerNumber>
      <postalAddress>postalAddress</postalAddress>
    </billTo>
  </header>
  <items>
    <publication xsi:type="cat:PublicationType">
      <title>title</title>
      <ddate>ddate</ddate>
    </publication>
    <description>description</description>
    <price>price</price>
    <discount>discount</discount>
  </items>
</invxsd:Invoice>
